name = "QMCGenerators"
uuid = "fcae8fc2-2969-4f4b-b6c9-a95746d81969"
authors = ["alegresor agsorokin3@gmail.com"]
version = "1.5.1"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DelimitedFiles = ">=1"
LaTeXStrings = ">=1"
julia = ">=1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
