name = "QMCGenerators"
uuid = "fcae8fc2-2969-4f4b-b6c9-a95746d81969"
authors = ["your-name"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
